[enh] Support dired-dwim-target
zevlg/telega.el pull request #322
Opened 2021-11-01 13:08 UTC by akater

Optionally guess default directory from dired buffers when picking
attachments.  By default, inherit user's `dired-dwim-target`
setting (dynamically).

In `telega-describe-chat--inserter` you set dir to nil explicitly.  I did not change that.

2021-11-01 14:34 UTC, zevlg requested changes

2021-11-01 14:34 UTC, zevlg commented on telega-chat.el
> +(defun telega--read-file-name (prompt &optional dir default-filename
This should be in the `telega-util.el` file along with other `telega-read-XXX` functions.  Make it public, i.e. `telega-read-file-name`

2021-11-01 14:34 UTC, zevlg commented on telega-chat.el
> +  "Like `read-file-name' but taking `telega-dired-dwim-target' into account."
Value for the `dir` argument should be regarded, i.e. second argument for the `read-file-name` should be in the form `(or dir XXX)`, so if `dir` is explicitly specified it should take precedence before other logic

2021-11-01 14:34 UTC, zevlg commented on telega-customize.el
> +(defcustom telega-dired-dwim-target 'inherit
Sounds a bit complicated. Maybe make its non-nil value to be value for the `dired-dwim-targed` in the `telega-read-file-name` ?   This will simplifies code overall, like:

```
(defcustom telega-dired-dwim-target dired-dwim-target ...)
```
and then in the `telega-read-file-name` we will have
```
(or dir
    (when telega-dired-dwim-target
      (let ((dired-dwim-target telega-dired-dwim-target))
        (dired-dwim-target-directory))))
```
for the second argument to the `read-file-name`

2021-11-02 10:35 UTC, akater commented on telega-customize.el
> +(defcustom telega-dired-dwim-target 'inherit
1. I'm fine with this and I also suggest we drop `defcustom telega-dired-dwim-target` altogether and just use user's preference for `dired-dwim-target`.

If we keep it to bind `dired-dwim-target` to its value unconditionally, it'd make sense then to inherit everything from `defcustom dired-dwim-target`, including its `type` so we'd have to use `custom-declare-variable` rather than `defcustom` which might be undesirable.

2. If we nevertheless keep the defcustom, maybe no need for `when` then?  `dired-dwim-target-directory` will return nil if `dired-dwim-target` is bound to nil.  Unless it's called from a dired buffer in which case it'll offer current dir but looks like it should not be an issue.

2021-11-02 10:53 UTC, zevlg commented on telega-customize.el
> +(defcustom telega-dired-dwim-target 'inherit
Or maybe create `telega-read-file-dir-function` custom variable instead to be a function returning directory?  So it could be `dired-dwim-target-directory` if user wants to utilize `dired-dwim-target` option

This looks like most flexible way, so someone could implement other logic, for example looking at file read history and taking most usable base directory, or any other logic

2021-11-02 12:17 UTC, akater commented on telega-customize.el
> +(defcustom telega-dired-dwim-target 'inherit
This option is anticipated in `dired-dwim-target` proper and some reasonable choices are offered in its `custom` interface so it's arguably preferrable to reuse it via `custom-variable-type` which would also automatically adjust to dired-dwim feature as provided by Emacs, whatever the Emacs version is.

If `custom-declare-variable` is appropriate, this amounts to

```lisp
(custom-declare-variable
 'telega-dired-dwim-target
 dired-dwim-target
 "*Value to bind `dired-dwim-target' to, in telega file pickers."
 :type
 (custom-variable-type 'dired-dwim-target)
 :group 'telega-chat)
```

Since `custom-declare-variable` is public, I consider this the best approach.

2021-11-02 12:41 UTC, zevlg commented on telega-customize.el
> +(defcustom telega-dired-dwim-target 'inherit
Okay, I'm good with either way: `telega-dired-dwim-target` with `custom-descrare-variable` or just `telega-read-file-dir-function` user option.

But keeping `(when telega-dired-dwim-target ...)` is essential I think, because we do not rely on `dired-dwim-target-directory` logic returning nil, just because major mode is not dried.  We rather explicitly specify that if `telega-dired-dwim-target` is unset, then `dir` is nil

2021-11-02 13:27 UTC, merged

2021-11-02 13:28 UTC, zevlg commented
Merged in, thanks for the contribution!