Introduce contrib/telega-bridge-bot.el
zevlg/telega.el pull request #395
Opened 2023-03-03 17:13 UTC by BlindingDark

Hi there.

This package will replace the message bridge bot (like @matrix_t2bot) to make it look like the user itself.
Please have a look!

Thanks! :pray:

2023-03-03 21:06 UTC, zevlg requested changes
Thank you for this awesome contribution!  I've added few comments on the code.

In general, it is better to use objects itself, such as `chat`, `user`, `message` instead of using id to reference these objects.  Properties of the objects changes sometimes in the TDLib, so code that references object properties directly is much more fragile in comparison to code that uses abstractions provided by `telega`.

It is fully okay to have this code as initial commit, however, I think the default value for `telega-bridge-bot-bridge-info-plist` user option should not be forced and should be configured by user of the package

2023-03-03 21:06 UTC, zevlg commented on contrib/telega-bridge-bot.el
> +  (let* ((mtime (nth 5 (file-attributes path)))
Use `file-attribute-modification-time` instead of `(nth 5 ...)`

2023-03-03 21:06 UTC, zevlg commented on contrib/telega-bridge-bot.el
> +  '(-1001773572820 ; @emacs_china
Better to use `nil` as default value. You can provide this sample configuration in the `:options` attribute in the `defcustom` as a reference

Having this default value might surprise users

2023-03-03 21:06 UTC, zevlg commented on contrib/telega-bridge-bot.el
> +             (nth 5 (file-attributes file-path))
Better to use `file-attribute-modification-time` instead of `(nth 5 ...)`

2023-03-03 21:06 UTC, zevlg commented on contrib/telega-bridge-bot.el
> +          (telega--tl-get (telega-user-get bot-id) :usernames :editable_username))
Use `telega-msg-sender-username` instead of getting username directly from the user properties

2023-03-03 21:06 UTC, zevlg commented on contrib/telega-bridge-bot.el
> +              (bot-id (telega--tl-get msg :sender_id :user_id))
To get a message sender better to use `(telega-msg-sender msg)` instead of referencing t `:sender_id`

2023-03-04 09:36 UTC, BlindingDark commented
Hi @zevlg . Thanks for your advice, I just pushed the changes, please have a look.

2023-03-04 11:58 UTC, merged

2023-03-04 11:59 UTC, zevlg commented
Merged in, thank you for this contribution!