Remove duplicate spaces when user has only first_name.
zevlg/telega.el pull request #426
Opened 2023-08-19 07:22 UTC by BlindingDark

If the user only sets the first_name, there will be extra spaces displayed.
This PR intends to fix it.

2023-08-19 21:18 UTC, zevlg requested changes

2023-08-19 21:18 UTC, zevlg commented on telega-user.el
> +                        (mapconcat #'identity
This version generates more garbage, probably something like `(when (and first-name last-name)` as condition for extra space is better?

2023-08-20 13:43 UTC, BlindingDark commented on telega-user.el
> +                        (mapconcat #'identity
Thanks @zevlg, I just updated the code, please review :pray:

2023-08-20 15:36 UTC, merged

2023-08-20 15:36 UTC, zevlg commented
Merged in, thanks for your effort!