show number of reaction type only if there are more than 3
zevlg/telega.el pull request #466
Opened 2024-04-01 18:36 UTC by macovsky

what do you think about such cosmetic change?

IMO this way it looks better since user sees up to three avatars anyways

2024-04-01 20:50 UTC, zevlg commented
There are few things to consider about this modification:
1) For blind telega users it is very useful to see number of reactions before taking any action, so this must be customizable after all
2) Recent reaction senders are not always available, so you won't be able to distinguish single reaction from double reaction
3) User might customize `telega-avatar-text-function`, so in nox-emacs he might not see recent reactions avatars at all even if the list of recent reaction senders is available

It is better to advice `telega-ins--msg-reaction` to implement custom behaviour you need

2024-04-03 10:58 UTC, macovsky commented
> There are few things to consider about this modification:
> 
> 1. For blind telega users it is very useful to see number of reactions before taking any action, so this must be customizable after all
> 2. Recent reaction senders are not always available, so you won't be able to distinguish single reaction from double reaction
> 3. User might customize `telega-avatar-text-function`, so in nox-emacs he might not see recent reactions avatars at all even if the list of recent reaction senders is available

good points of course, thanks for going into details!

> It is better to advice `telega-ins--msg-reaction` to implement custom behaviour you need

will try to make it!

2024-04-09 06:37 UTC, macovsky commented
@zevlg added a customization option like you adviced

2024-04-09 06:45 UTC, zevlg requested changes
This looks decent!

2024-04-09 06:45 UTC, zevlg commented on telega-customize.el
> +  "Inserter for message reaction."
Add please `:package-version` tag to this user option

2024-04-09 06:52 UTC, macovsky commented on telega-customize.el
> +  :package-version '(telega . "0.8.255")
is this a correct one?

2024-04-09 21:24 UTC, zevlg commented on telega-customize.el
> +  :package-version '(telega . "0.8.255")
No, unless you change `telege-version` in the telega.el, put last `telega-version` , i.e. `0.8.254`

2024-04-10 06:29 UTC, macovsky commented on telega-customize.el
> +  :package-version '(telega . "0.8.255")
got it, fixed!

2024-04-10 09:28 UTC, merged