[fix] add missing interactive to transient-define-prefix
zevlg/telega.el pull request #473
Opened 2024-04-26 12:44 UTC by HyperSuperMetaCtrl

without this telega does not start anymore
Addresses Issue #472

2024-04-26 12:54 UTC, HyperSuperMetaCtrl commented
Starting telega with `M-x` returned:
```
internal-macroexpand-for-load: Eager macro-expansion failure: (error "transient-define-*: Interactive form missing")
```
I then turned on `tooggle-debug-on-error` and got:
```
Debugger entered--Lisp error: (error "Eager macro-expansion failure: (error \"transient-d...")
  error("Eager macro-expansion failure: %S" (error "transient-define-*: Interactive form missing"))
  internal-macroexpand-for-load((transient-define-prefix telega-saved-messages-tag-commands (tag) [:description (lambda nil (telega-ins--as-string (telega-ins--saved-messages-tag (car (oref transient--prefix scope))) (telega-ins--with-face 'transient-heading (telega-ins "Tag Commands")))) (telega-saved-messages-tag-filter) (telega-saved-messages-tag-add-name) (telega-saved-messages-tag-remove)] (lambda (tag) (interactive (list (user-error "Do not call this command directly"))))) nil)
  load-with-code-conversion("/home/me/.config/emacs/.local/straight/build-2..." "/home/me/.config/emacs/.local/straight/build-2..." nil t)
  require(telega-util)
  load-with-code-conversion("/home/me/.config/emacs/.local/straight/build-2..." "/home/me/.config/emacs/.local/straight/build-2..." nil t)
  require(telega-root)
  load-with-code-conversion("/home/me/.config/emacs/.local/straight/build-2..." "/home/me/.config/emacs/.local/straight/build-2..." nil t)
  command-execute(telega record)
  execute-extended-command(nil "telega" nil)
  funcall-interactively(execute-extended-command nil "telega" nil)
  command-execute(execute-extended-command)
```
Then added `(interactive)` to `transient-define-prefix` in `telega-util.el`.

With this change telega starts as usual.

2024-04-27 20:19 UTC, rudolf-adamkovic commented
I can confirm that this works.

Thanks @HyperSuperMetaCtrl for figuring out the problem!

2024-04-28 08:09 UTC, HyperSuperMetaCtrl commented
Happy to help

2024-04-28 08:30 UTC, zevlg requested changes

2024-04-28 08:30 UTC, zevlg commented on telega-util.el
> +  (interactive)
I think there should be a docstring for this transient prefix, not `(interactive)`.  `telega-saved-messages-tag-commands` is not supposed to be called interactive

2024-04-28 09:14 UTC, HyperSuperMetaCtrl commented on telega-util.el
> +  (interactive)
Hey zevlg,
thank you for your feedback.
What do you mean exactly? Should I add a docstring, that warns about not using this function interactively, or do you want it to be solved in a different way, because this transient prefix is not supposed to be called interactively?

2024-04-28 09:17 UTC, zevlg commented on telega-util.el
> +  (interactive)
In the place where you've added `(interactive)` should be a docstring for the transient prefix.  `(interactive)` works because it adds missing argument and docstrings are ignored.  So just replace `(interactive)` with the docstring

2024-04-28 09:40 UTC, HyperSuperMetaCtrl commented on telega-util.el
> +  (interactive)
Just replacing the `(interactive)` with a string leads to the same error as before for me. But my elisp is quite limited. So this could just be a skill issue on my side

2024-04-28 11:20 UTC, HyperSuperMetaCtrl commented
Found a way to do this without adding `(interactive)`
closing

2024-04-28 11:20 UTC, closed without merging